typedef NS_ENUM(NSInteger, NTKFaceStyle) {
/*  0 */	NTKFaceStyleUtility,
/*  1 */	NTKFaceStyleSimple,
/*  2 */	NTKFaceStyleChronograph,
/*  3 */	NTKFaceStyleColor,
/*  4 */	NTKFaceStyleModular,
/*  5 */	NTKFaceStylePhoto,
/*  6 */	NTKFaceStyleMotion,
/*  7 */	NTKFaceStyleTimelapse,
/*  8 */	NTKFaceStyleSolar,
/*  9 */	NTKFaceStyleAstronomy,
/* 10 */	NTKFaceStyleMickey,
/* 12 */	NTKFaceStyleXLarge = 12,
/* 13 */	NTKFaceStyleAlbum,
/* 14 */	NTKFaceStyleZeusAnalog,
/* 16 */	NTKFaceStyleActivityAnalog = 16,
/* 17 */	NTKFaceStyleActivityDigital,
/* 18 */	NTKFaceStyleNumeralsAnalog,
/* 19 */	NTKFaceStyleVictoryAnalog,
/* 20 */	NTKFaceStyleVictoryDigital,
/* 21 */	NTKFaceStyleUpNext,
/* 22 */	NTKFaceStylePhotos,
/* 23 */	NTKFaceStyleKaleidoscope,
/* 24 */	NTKFaceStyleExplorer,
/* 25 */	NTKFaceStyleInfinity,
/* 26 */	NTKFaceStylePride,
/* 27 */	NTKFaceStyleBreathe,
/* 28 */	NTKFaceStyleVapor,
/* 29 */	NTKFaceStyleInfographModular,
/* 30 */	NTKFaceStyleInfograph,
/* 31 */	NTKFaceStyleMetallic,
/* 32 */	NTKFaceStyleFireWater,
/* 33 */	NTKFaceStylePrideAnalog,
/* 34 */	NTKFaceStyleWhistlerSubdials,
/* 35 */	NTKFaceStyleOlympus,
/* 36 */	NTKFaceStyleSidereal,
/* 37 */	NTKFaceStyleBigNumeralsDigital,
/* 38 */	NTKFaceStyleBigNumeralsAnalog,
/* 39 */	NTKFaceStyleCalifornia,
/* 40 */	NTKFaceStyleBlackcomb,
/* 41 */	NTKFaceStyleSpectrumAnalog,
/* 42 */	NTKFaceStyleWhitetank,
/* 256 */	NTKFaceStyleCustom = 0x100
};